package act.util;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Mark a class eligible to auto generation on {@link Object#equals(Object)}
 * and {@link Object#hashCode()}.
 */
@Retention(RetentionPolicy.CLASS)
@Target(ElementType.TYPE)
public @interface AutoObject {
    /**
     * Whether the generated {@code equals} and {@code hashCode}
     * method should call super.
     * <p>If not specified, then super method will not be called</p>
     * @return {@code true} if super should be called in autogenerated
     *         methods
     */
    boolean callSuper() default false;
}
